title: Won's Blog
email: gjehdtjr911@gmail.com
description: >-
  This is my personal blog.
baseurl: "/NOTE"
url: ""
github_username: POBSIZ

theme: minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

permalink: pretty

collections:
  posts:
    output: true
    permalink: /:categories/:title

sass:
  style: compressed
  load_paths:
    - _sass
