title: Won's Blog
email: gjehdtjr911@gmail.com
description: >-
  Blog.
baseurl: "/NOTE"
url: ""
github_username: POBSIZ

theme: minima
# remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

include:
  - _posts
  - assets

exclude:
  - node_modules
  - vendor
  - Gemfile

future: true # 미래 날짜의 게시글을 표시하려면 true로 설정

permalink: pretty

collections:
  posts:
    output: true
    permalink: /:categories/:title

sass:
  style: compressed
  load_paths:
    - _sass

google_analytics: G-S7P63BDB2V
