title: Won's Blog
email: gjehdtjr911@gmail.com
description: >-
  This is my personal blog.
baseurl: "/NOTE"
url: ""
github_username: POBSIZ

theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /:categories/:title/
