source "https://rubygems.org"

gem "jekyll", "~> 3.8"
gem "jekyll-theme-minima"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-paginate"  # 페이지네이션
  gem "jekyll-seo-tag"  # SEO 태그 자동 생성
  gem "jekyll-sitemap"
  gem "jekyll-remote-theme"
  gem "github-pages"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
